name: pos_desktop_clean
description: "Flutter Desktop POS (Clean Architecture)"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  intl: ^0.19.0
  google_fonts: ^6.2.1
  collection: ^1.18.0
  get_it: ^7.7.0
  go_router: ^14.2.0
  flutter_secure_storage: ^9.2.2
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
